### ISSUE TITLE
Choosing a license?

### ISSUE THREAD

**Issue by NepNep21** [ThadHouse/gradle-compile-commands#1]
Hello! I would like to fork this project, however it currently does not state an explicit license, and as such is effectively all rights reserved. May you choose a FOSS license or allow me to fork it in some other way?

**Comment by qe7** [comment]
Suck ur mum

**Comment by ThadHouse** [comment]
I’ll put an MIT license on this tonight.

**Comment by NepNep21** [comment]
Thank you!

**Comment by qe7** [comment]
NepNep21 I deeply love you please accept my love.

**Comment by ThadHouse** [comment]
License is created.
